version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  bet-maker:
    image: ghcr.io/wladbelsky/bet-maker/bet-maker:master
    restart: on-failure
    environment:
      WEB_SERVER_HOST: ${WEB_SERVER_HOST}
      WEB_SERVER_PORT: 8080
      DB_ENGINE: postgresql+asyncpg
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
    depends_on:
        - db
    ports:
      - "8080:8080"